model:
  name: segnext-large
  pretrained_checkpoint: null # Set this to the cityscapes weights path in Kaggle
  num_classes: 26
  image_size: 1024

dataset:
  name: idd
  ignore_index: 255
  reduce_labels: false

training:
  epochs: 30
  train_batch_size: 2
  val_batch_size: 2
  learning_rate: 0.00003
  weight_decay: 0.01
  warmup_ratio: 0.1
  gradient_accumulation_steps: 4
  save_strategy: epoch
  eval_strategy: epoch
  logging_steps: 50
  seed: 42
  save_total_limit: 3
  dataloader_num_workers: 4
  early_stopping_patience: 10   # stop when mIoU doesn't improve

optimizer:
  name: adamw
  betas: [0.9, 0.999]
  eps: 1.0e-8

scheduler:
  name: polynomial
  power: 0.9
  min_lr: 0.0

paths:
  image_root: /kaggle/input/datasets/abhishekprajapat/idd-20k/idd20k_final
  label_root: /kaggle/input/datasets/abhishekprajapat/idd-20k/idd20k_final
  train_split: /kaggle/working/splits/train.txt
  val_split: /kaggle/working/splits/val.txt
  test_split: data/splits/test.txt
  output_dir: /kaggle/working/outputs/segnext_large
  best_model_dir: /kaggle/working/outputs/segnext_large/best_model

hardware:
  fp16: true
  num_workers: 4
  pin_memory: true

hamburger:
  ham_channels: 512
  put_cheese: true
  DUAL: false
  SPATIAL: true
  RAND_INIT: true
  MD_S: 1
  MD_D: 512
  MD_R: 64
  TRAIN_STEPS: 6
  EVAL_STEPS: 6
  INV_T: 1
  BETA: 0.1
  Eta: 0.9
